name: build_ErfanGSIs

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'ROM_URL'
        required: true
        default: 'https://hugeota.d.miui.com/21.5.31/miui_TUCANA_21.5.31_cb42ec9bed_11.0.zip'
      ROM_NAME:
        description: 'ROM_NAME'
        required: true
        default: 'Generic'
      BUILD_TYPE: 
        description: 'BUILD_TYPE(--ab or --aonly)
        required: true
        default: '--ab'
  watch:
    types: [started]
    
env:
  ROM_URL: https://www.coolapk.com/link?url=https%3A%2F%2Fsysupwsdl.vivo.com.cn%2Fupgrade%2Fupload%2FUpdateFiles%2F20201215073327bbcb7082271631abb20e994c8a02cb86.zip
  ROM_NAME: Generic
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo apt install python3
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd  $GITHUB_WORKSPACE/ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
              touch info.txt
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip


       - name: Upload to Release‌‌...
         uses: ncipollo/release-action@v1.8.0
         with: |
           artifacts: "${{ github.workspace }}/ErfanGSIs/output/*"
           tag: "${{ github.workspace }}/ErfanGSIs/info.txt"
           bodyFile: "${{ github.workspace }}/ErfanGSIs/info.txt"
           token: "${{ secrets.GITHUB_TOKEN }}"
       

            
