name: build_ErfanGSIs

on: 
  watch:
    types: [ started ]
    
    
env:
  ROM_URL: https://firmware.meizu.com/Firmware/Flyme/meizu17/9.3.0.0/cn/20220628162927/e5eec5f7/update.zip
  ROM_NAME: Generic
  BUILD_TYPE: ab
  TZ: Asia/Shanghai
  REPACK_NAME: GSI.zip


jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' ErfanGSIs/url2GSI.sh
       
       - name: Setting up requirements
         run: |
              cd ErfanGSIs
              mkdir ./output
              sudo apt install python3-pip
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       - name: Pack GSI
         run: |
              zip -r ErfanGSIs/output/GSI.zip ErfanGSIs/output/*
              cd ErfanGSIs/output
              split
              split -b 1024m GSI.zip Splited_
       
       - name: Upload GSI
         run: |
              cd ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./*
        
 


            
