name: build_ErfanGSIs

on: 
  watch:
    types: [ started ]
    
    
env:
  ROM_URL: https://060enccmsnnlea610ktf0ssldqmnjpqotah4j0v25atfrhmhc0gvvs6c.qc.x.bsgslb.cn:10443/xdispatch65565077deb8532e/bigota.d.miui.com/V12.0.1.0.PDEMIXM/miui_MIMIX2Global_V12.0.1.0.PDEMIXM_64006b3102_9.0.zip?bsreqid=b9201e8b0914383b016c9194c8a2d546
  ROM_NAME: MIUI
  BUILD_TYPE: ab
  TZ: Asia/Shanghai
  REPACK_NAME: GSI.zip


jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' ErfanGSIs/url2GSI.sh
       
       - name: Setting up requirements
         run: |
              cd ErfanGSIs
              mkdir ./output
              sudo apt install python3-pip
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       - name: Pack GSI
         run: |
              zip -r ErfanGSIs/output/GSI.zip ErfanGSIs/output/*
              cd ErfanGSIs/output
              split
              split -b 1024m GSI.zip Splited_
       
       - name: Upload GSI
         run: |
              cd ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./*
        
 


            
